#!/usr/bin/env php
<?php

declare(strict_types=1);

use Ssc\Dtk\Infrastructure\Symfony\AppKernel;
use Ssc\Dtk\Infrastructure\Symfony\DtkCli;
use Ssc\Dtk\Infrastructure\Symfony\DtkHelpCommand;
use Ssc\Dtk\Infrastructure\Symfony\Version;
use Ssc\Dtk\Infrastructure\Symfony\DtkCommandDescriptor;
use Symfony\Bundle\FrameworkBundle\Console\Application;

if (!is_dir(__DIR__.'/vendor')) {
    throw new LogicException('Dependencies are missing. Try running "composer install".');
}

if (!is_file(__DIR__.'/vendor/autoload_runtime.php')) {
    throw new LogicException('Symfony Runtime is missing. Try running "composer require symfony/runtime".');
}

require_once __DIR__.'/vendor/autoload_runtime.php';

return static function (array $context): DtkCli {
    $kernel = new AppKernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);
    $application = new Application($kernel);

    // Register only DTK commands (listed in DtkCli::COMMANDS),
    // excluding Symfony framework commands (cache:clear, debug:*, etc.).
    $dtk = new DtkCli('dtk', Version::VERSION);
    foreach (array_keys(DtkCli::COMMANDS) as $name) {
        $dtk->addCommand($application->get($name));
    }

    // Wire up the event dispatcher so that monolog's ConsoleHandler can capture the output
    $dtk->setDispatcher($kernel->getContainer()->get('event_dispatcher'));

    // Replace Symfony HelpCommand with our own, to customise the output
    $dtk->addCommand(new DtkHelpCommand(new DtkCommandDescriptor(), $dtk));

    return $dtk;
};
